version: '3'

services:
  backend:
    container_name: meli-app
    build:
      dockerfile: Dockerfile
      context: .
      args:
        GO_VERSION: '1.19'
    volumes:
      - .:/meli
    environment:
      API_SERVER_ADDR: ":8080"
    ports:
      - "8080:8080"
    networks:
      - melinet
    depends_on:
      - "mongodb"
    env_file:
      - .env
  mongodb:
    container_name: meli-mongodb
    image: mongodb/mongodb-community-server:6.0-ubi8
    volumes:
      - dbdata:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: melidb
    networks:
      - melinet
  web:
    container_name: meli-nginx
    build: ./nginx
    volumes:
      - ./frontend/build:/meli/frontend/build
    ports:
      - "80:80"
      - "40:40"
    networks:
      - melinet
    depends_on:
      - backend
      - frontend
  frontend:
    container_name: meli-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./frontend:/meli
      - /meli/node_modules
    ports:
      - "3000:3000"
    networks:
      - melinet
    depends_on:
      - backend

networks:
  melinet:
    name: melinet

volumes:
  dbdata:
    name: meli-mongodb-data