version: '3'

services:
  meli-challange:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        GO_VERSION: '1.19'
    volumes:
      - .:/meli-challange
    environment:
      API_SERVER_ADDR: ":8080"
    ports:
      - "8080:8080"
