version: '3'

services:
  meli:
    container_name: meli-app
    build:
      dockerfile: Dockerfile
      context: .
      args:
        GO_VERSION: '1.19'
    volumes:
      - .:/meli
    environment:
      API_SERVER_ADDR: ":8080"
    ports:
      - "8080:8080"
    networks:
      - melinet
    depends_on:
      - "mongodb"
  mongodb:
    container_name: meli-mongodb
    image: mongodb/mongodb-community-server:6.0-ubi8
    volumes:
      - dbdata:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: melidb
    networks:
      - melinet
  web:
    container_name: meli-nginx
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - melinet
    depends_on:
      - meli

networks:
  melinet:
    name: melinet

volumes:
  dbdata:
    name: meli-mongodb-data